(function(g){var window=this;var Woa=function(a){a.u||(a.u=new g.An,g.C(a,a.u));return a.u},K2=function(a){a.R("cardstatechange",g.yL(a)&&g.zL(a)?1:0)},Xoa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.dk&&a.dataset){if(g.ic()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.hd("pollChoiceIndex"))},Yoa=function(a){return Math.pow(a,3)},Zoa=function(a){return 3*a*a-2*a*a*a},L2=function(a,b){(0,g.z)(b,function(c){c={csn:a,
ve:g.Zr(c),eventType:4};var d={Lj:void 0,Th:a};"UNDEFINED_CSN"==a?g.js("visualElementShown",c,d):g.mr("visualElementShown",c,g.tr,d)})},M2=function(a,b){(0,g.z)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Zr(c),eventType:d?16:8};d={Lj:void 0,Th:a,CD:d};"UNDEFINED_CSN"==a?g.js("visualElementHidden",c,d):g.mr("visualElementHidden",c,g.tr,d)})},P2=function(a){a=g.Na(a);
delete N2[a];g.Yb(N2)&&O2&&O2.stop()},apa=function(){O2||(O2=new g.J(function(){$oa()},20));
var a=O2;a.isActive()||a.start()},$oa=function(){var a=(0,g.H)();
g.Lb(N2,function(b){bpa(b,a)});
g.Yb(N2)||apa()},Q2=function(a,b,c,d){g.nn.call(this);
if(!g.Ia(a)||!g.Ia(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.M=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},bpa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;cpa(a,a.progress);1==a.progress?(a.o=0,P2(a),a.jd(),a.A()):1==a.o&&a.As()},cpa=function(a,b){g.Ka(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.M[c]-a.w[c])*b+a.w[c]},dpa=function(a,b){g.le.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},R2=function(a,b,c,d,e){Q2.call(this,b,c,d,e);
this.element=a},S2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
R2.call(this,a,b,c,d,e)},T2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},epa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.br(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},U2=function(a){return a.baseUrl||null},fpa=function(a,b,c){function d(wb){var Ya=wb.hovercardButton;
if(!Ya)return null;Ya=Ya.subscribeButtonRenderer;if(!Ya)return null;var uc=f(Ya.unsubscribedButtonText),ff=f(Ya.subscribedButtonText);if(Ya.subscribed){var gf=f(Ya.subscriberCountWithUnsubscribeText);var Bh=f(Ya.subscriberCountText)}else gf=f(Ya.subscriberCountText),Bh=f(Ya.subscriberCountWithSubscribeText);var hf=null;return wb.signinEndpoint&&(hf=g.Tb(wb,"signinEndpoint","webNavigationEndpointData","url"),!hf)?null:uc&&(ff||hf)?{subscribed:Ya.subscribed,subscribeText:uc,subscribeCount:gf,unsubscribeText:ff,
unsubscribeCount:Bh,enabled:Ya.enabled,signinUrl:hf,classic:wb.useClassicSubscribeButton}:null}
function e(wb){if(wb){var Ya=[],uc=wb.videoId;uc&&Ya.push("v="+uc);(uc=wb.playlistId)&&Ya.push("list="+uc);(wb=wb.startTimeSeconds)&&Ya.push("t="+wb);return"/watch?"+Ya.join("&")}}
function f(wb){if(!wb)return null;var Ya=wb.simpleText;return Ya?Ya:wb.runs?(0,g.Ic)(wb.runs,function(uc){return uc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,y=null,B=!1,D=null,G=null,F=null,E=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Tb(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?D=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Tb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Tb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Tb(b,"title","accessibility","accessibilityData","label");var aa=b.endpoint?b.endpoint.clickTrackingParams:null,eb="";if(b.metadata){var tc=f(b.metadata);tc&&(eb=tc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:eb,callToAction:f(b.callToAction),
Gv:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:y,subscribeButton:D,subscribersText:G,isSubscribe:B,targetUrl:m,cF:n,Jb:{itct:aa},VN:q,Bj:a?a:null,gF:b.isPlaceholder,impressionUrls:(0,g.Ic)(b.impressionUrls||[],U2),TE:(0,g.Ic)(b.hovercardShowUrls||[],U2),clickUrls:(0,g.Ic)(l.loggingUrls||[],U2),visualElement:g.Yr(b.trackingParams),
productPrice:E,additionalFeesText:M}},V2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.Ic)(a.impressionUrls||[],U2);a.trackingParams&&(c.visualElement=g.Yr(a.trackingParams));var d=(0,g.Ic)(a.elements||[],function(e,f){return fpa(b,e,f)});
c.elements=(0,g.Yd)(d,function(e){return!!e});
return c},W2=function(a){g.AP.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.P();this.M=g.Mx(a)||g.Ox(a);this.J=!0;this.G=0;this.B=new g.P(this);g.C(this,this.B);this.B.L(this.player,g.dE("creatorendscreen"),this.OF);this.B.L(this.player,"crx_creatorendscreen",this.PF);this.B.L(this.player,"resize",this.Mx);this.B.L(window,"focus",this.VM);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ie(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},gpa=function(a){return a.player.getVideoData().jc?"current":a.M?"new":"current"},X2=function(a){return"creator-endscreen-editor"===a.player.P().playerStyle},Y2=function(a,b,c){c=void 0===c?!0:c;
g.PQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&hpa(a);c=[];d=new g.aE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.P().o||(a.w=new g.V({D:"div",I:"ytp-ce-shadow"}),g.JL(a.player,a.w.element,4),a.C=new g.cM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=ipa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.JL(a.player,f.element,4);var k=new g.aE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);jpa(a,f,e)}g.FL(a.player,c);
a.Mx()}},hpa=function(a){var b=g.ys(),c=g.zs();
c&&b&&a.u.visualElement&&g.ks(c,b,[a.u.visualElement],void 0)},ipa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.Bj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:Z2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:$2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.tn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.Bj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:Z2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:$2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.tn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.Bj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],N:{href:$2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.tn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Z2(b)}]};c=new g.V(c);var d=g.Ed(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.P().o){var e=null;var f=b.Jb.itct}else e="endscreen",f=null;e=new g.fQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.Bj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",N:{dir:g.tn(b.title||"")},V:b.title},{D:"div",I:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],N:{href:$2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Z2(b)},{D:"div",I:"ytp-ce-expanding-icon",N:kpa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.Bj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",N:{dir:g.tn(b.title||"")},V:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:$2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Z2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.V(c)}b.gF&&g.K(c.element,"ytp-ce-placeholder");return c},Z2=function(a){if(a.Gv)var b=a.Gv.thumbnails;
return kpa(b?b[b.length-1].url:null)},kpa=function(a){return a?{style:"background-image: url("+a+")"}:{}},jpa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ha("mouseenter",(0,g.x)(a.zr,a,b,c));b.ha("mouseleave",(0,g.x)(a.Fs,a,b,c));a.player.P().o||b.ha("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ha("click",(0,g.x)(a.uz,a,c));b.ha("keypress",(0,g.x)(a.uz,a,c));b.ha("focus",(0,g.x)(function(l,m){this.zr(l,m)},a,b,c));
b.ha("blur",(0,g.x)(function(l,m){this.Fs(l,m)},a,b,c));
b.ha("touchstart",(0,g.x)(a.zr,a,b,c));var f=g.Gd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.ln(b.element,"ytp-ce-element-hover");g.ln(b.element,"ytp-ce-force-expand")});
b.ha("keydown",(0,g.x)(function(l,m){this.J=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),a3(this,m.id,!0)):(g.ln(l.element,"ytp-ce-force-expand"),g.ln(l.element,"ytp-ce-element-hover"),a3(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ha("blur",g.Oa(function(){"none"!=m.style.display&&a.J&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Gd("ytp-sb-subscribe",b.element));c(g.Gd("ytp-sb-unsubscribe",b.element));b.ha("focus",d);b.ha("blur",e)},$2=function(a,b){var c=a.player.P();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.my(c)+b}else return"";return b},a3=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},b3=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||X2(a))c&&c();else{b=lpa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.eq(b[a],d)}},c3=function(a,b,c){b3(a,b.clickUrls,c);
(a=g.zs())&&b.cF&&g.ms(a,b.visualElement)},lpa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(mpa(b[e],c));return d},mpa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},npa=function(a){return g.Ia(a)&&a.length?a[0]:a},d3=function(a){return"string"===typeof a?a:""},e3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},ppa=function(a){var b=opa;
if(null==a)return null;if(g.Ja(a)){var c=[];(0,g.z)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},qpa=function(a){this.externalId=a},rpa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},f3=function(a){if(!a)return null;
var b=g.Cc(d3(a.value));b=g.Ac(b);if(!b)return null;var c=e3(a.target,spa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new rpa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},g3=function(a){return a.value?a.value:null},tpa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},opa=function(a){if(!a)return null;
var b=e3(a.type,upa),c=e3(a.trigger,vpa),d=npa(a.url);d=f3(d?d:null);a=npa(a.subscribeData);var e=a?a:null;e?(a=d3(e.external_user_id),e=d3(e.subscription_token),a=a&&e?new qpa(a):null):a=null;return b?new tpa(b,c,d,a):null},wpa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},ypa=function(a){return(a=xpa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},xpa=function(a,b){return g.Va(a.o,b,void 0)},zpa=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Apa=function(a,b){this.merchant=a;
this.price=b},Bpa=function(a){this.o=a},Cpa=function(a,b,c){b&&(c?h3(a,(0,g.Ic)(b,g.Oa(function(d,e){return g.Vm(e,d)},c))):h3(a,b))},h3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.z)(b||[],function(m){e++;
g.eq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Dpa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.gb=c;this.videoData=d;this.logger=e;this.ca=f;this.u=k},i3=function(a,b){this.o=a;
this.w=b},Gpa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Epa(b,k))},a);
var d={D:"ul",N:{role:"radiogroup"},K:c},e={};b.Xh&&(e["aria-label"]=g.IM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[j3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Xh&&(f.push("iv-card-unavailable"),d.push({D:"div",W:["iv-card-sign-in"],K:[{D:"h2",V:"Want to vote?"},{D:"a",W:["iv-card-sign-in-button","iv-button"],N:{href:g3(b.Xh)},K:[{D:"span",W:["iv-button-content"],V:"Sign in"}]}]}));f=new g.V({D:"div",
W:f,K:d});d=f.element;Fpa(b,d);epa(a.o.o,d,g.Oa(a.A,b),a);(0,g.z)(g.Fd("iv-card-poll-choice-input",d),function(k){this.o.o.ha(k,"focus",g.Oa(this.u,!0));this.o.o.ha(k,"blur",g.Oa(this.u,!1))},a);
b.Xh&&(d=g.Gd("iv-card-sign-in-button",d),a.w(d,b.Xh,b.id,b.Jb,b.Ac.click,5));return f},Hpa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.oO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.fF&&b.av?{D:"span",W:d,N:e,V:b.av}:"";c={D:"div",W:["iv-card",c],K:[{D:"a",I:"iv-click-target",N:{href:g3(b.url)},K:[k3(b.ai,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",V:b.title},l3(a,b)]}]}]};c=new g.V(c);m3(a,g.Fd("iv-click-target",c.element),b,b.url);return c},n3=function(a){return a.customMessage?
j3("div","iv-card-message",a.customMessage):""},k3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",N:{style:c},K:d}},l3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(j3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Epa=function(a,b){return{D:"li",
I:zpa(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},j3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},j3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ia(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.tn(c);return{D:a,N:b,V:c}},Ipa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.em&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.em+");");c.dir=g.tn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",W:b,N:c,K:d}},Fpa=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Gd(zpa(a,e.index),b);e=e.count/c;null==a.re&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.re==d);f.getElementsByTagName("input")[0].checked=a.re==d;var k=Math.floor(100*e).toFixed(0),l=g.Gd("iv-card-poll-choice-percent",f);g.be(l,g.IM("$PERCENT%",{PERCENT:k}));f=g.Gd("iv-card-poll-result-bar",f);g.qh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.re);g.L(b,"iv-card-poll-expanded",
null!=a.re&&1<a.choices.length)},m3=function(a,b,c,d){d&&(0,g.z)(b,function(e){this.w(e,d,c.id,c.Jb,c.Ac.click,5)},a)},Jpa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Kpa=function(a,b){return b?b:Jpa(a)?"current":"new"},o3=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.Pt=!1},Lpa=function(a,b,c,d,e){var f=g3(b);
if(f){var k=Kpa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ca.pauseVideo();var m=this.context.videoData.jc||!1,n=g.rp(f||"");m&&n&&(n.v||n.list)?g.nT(this.context.ca.app,n.v,c,n.list,!1,void 0):g.MM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);h3(a.context.logger,d,l,e);Jpa(f)||(a=g.zs(),d=c.itct,a&&d&&g.ms(a,g.Yr(d)))}},Mpa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},p3=function(a,b,c){return{Uw:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
hB:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Go:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},s3=function(a,b,c){o3.call(this,b,c);
var d=this;this.w=a;this.ea=this.Ba=this.C=this.Aa=!1;this.oa=null;this.Z=new g.J(g.Fa,c.gb.Ra?4E3:3E3);g.C(this,this.Z);this.ua=new g.J(g.Fa);g.C(this,this.ua);this.H=new i3(c,(0,g.x)(this.mj,this),(0,g.x)(this.ln,this));this.U=new g.V({D:"div",I:"iv-drawer",N:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.C(this,this.U);this.F=this.U.element;this.ka=new g.cM(this.U,330);g.C(this,this.ka);this.za=g.Gd("iv-drawer-header-text",this.F);this.B=g.Gd("iv-drawer-content",this.F);this.A=[];this.xa=this.T=this.G=this.fa=this.u=null;this.Y=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ba&&q3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ba=d.C)&&r3(d)});
this.O=this.M=this.aa=null;this.J=0},Npa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){q3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){r3(a)});
var c=b.data.headerText;g.be(a.za,c);a.T&&a.T.setAttribute("title",c);a.aa=g.Yr(b.data.trackingParams);a.O=g.Yr(b.data.closeTrackingParams);a.M=g.Yr(b.data.iconTrackingParams)},Opa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"simple",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Jb:t3(a,c,b,d),sponsored:!1,Ac:p3(d,e,d.command),Qd:d.trackingParams?g.Yr(d.trackingParams):null,Gd:e.trackingParams?
g.Yr(e.trackingParams):null,bd:f&&f.trackingParams?g.Yr(f.trackingParams):null,imageUrl:u3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.qA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,em:null,title:d.title?g.qA(d.title):"",customMessage:d.callToAction?g.qA(d.callToAction):"",url:d.command.urlEndpoint.url?f3({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.command.urlEndpoint.url}):null};v3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"collaborator",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Jb:t3(a,c,b,d),sponsored:!1,Ac:p3(d,e,d.endpoint),Qd:d.trackingParams?g.Yr(d.trackingParams):null,Gd:e.trackingParams?g.Yr(e.trackingParams):null,bd:f&&f.trackingParams?
g.Yr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.qA(d.customText):null,iA:u3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.qA(d.channelName):"",metaInfo:[d.subscriberCountText?g.qA(d.subscriberCountText):""],url:f3({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};v3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"playlist",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Jb:t3(a,c,b,d),sponsored:!1,Ac:p3(d,e,d.action),Qd:d.trackingParams?g.Yr(d.trackingParams):null,Gd:e.trackingParams?g.Yr(e.trackingParams):null,bd:f&&f.trackingParams?g.Yr(f.trackingParams):
null,ai:u3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.qA(d.customMessage):null,playlistVideoCount:g.qA(d.playlistVideoCount),title:d.playlistTitle?g.qA(d.playlistTitle):"",metaInfo:[d.channelName?g.qA(d.channelName):"",d.videoCountText?g.qA(d.videoCountText):""],url:f3({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Mpa(d.action)})};v3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"video",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Jb:t3(a,c,b,d),sponsored:!1,Ac:p3(d,e,d.action),Qd:d.trackingParams?g.Yr(d.trackingParams):null,Gd:e.trackingParams?g.Yr(e.trackingParams):null,bd:f&&f.trackingParams?g.Yr(f.trackingParams):null,ai:u3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.qA(d.lengthString):null,customMessage:d.customMessage?g.qA(d.customMessage):null,title:d.videoTitle?g.qA(d.videoTitle):"",metaInfo:[d.channelName?g.qA(d.channelName):"",d.viewCountText?g.qA(d.viewCountText):""],isLiveNow:!!d.badge,url:f3({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Mpa(d.action)})};v3(a,c)}a.J++},u3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},t3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},Qpa=function(a,b){var c=Ppa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Xd(c.Dp),g.cb(a.A,c),a.gm(),w3(a))},q3=function(a,b,c){if(!a.C){a.ka.show();
a.fa=new g.J(function(){g.K(g.pL(a.context.ca),"ytp-iv-drawer-open")},0);
a.fa.start();a.oa=g.Tq(a.B,"mousewheel",(0,g.x)(a.lG,a));a.C=!0;var d=g.zs();d&&a.aa&&a.O&&L2(d,[a.aa,a.O]);var e={TRIGGER_TYPE:b};(0,g.z)(a.A,function(f){f.yx||(f.yx=!0,Cpa(a.context.logger,f.card.Ac.Uw,e));d&&L2(d,[f.card.Qd])});
K2(a.w);c&&(a.G=new g.J(function(){a.ra=a.T;a.xa.focus()},330),a.G.start())}},r3=function(a){a.C&&(a.ka.hide(),g.Uq(a.oa),a.oa=null,g.ln(g.pL(a.context.ca),"ytp-iv-drawer-open"),a.C=!1,K2(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.ra&&(a.ra.focus(),a.ra=null)},330),a.G.start())},Rpa=function(a){var b=g.Gd("iv-drawer-close-button",a.F);
a.context.o.ha(b,"click",a.kD,a);a.context.o.ha(a.B,"touchend",function(){a.Z.start()});
a.context.o.ha(a.B,"scroll",a.yD,a);a.context.u.subscribe("onHideControls",function(){a.ea=!0});
a.context.u.subscribe("onShowControls",function(){a.ea=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ea=g.jn(g.pL(a.w),"ytp-autohide")});
a.Y.push(g.So("iv-button-shown",a.qF,a));a.Y.push(g.So("iv-button-hidden",a.pF,a));a.Y.push(g.So("iv-teaser-shown",a.tF,a));a.Y.push(g.So("iv-teaser-hidden",a.sF,a));a.Y.push(g.So("iv-teaser-clicked",a.rF,a))},v3=function(a,b){a.Aa||(g.kn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.JL(a.w,a.F,5),Rpa(a),a.T=g.Gd("ytp-cards-button",g.pL(a.w)),a.xa=g.Gd("iv-drawer-close-button",a.F),a.Aa=!0);Qpa(a,b.id);var c=Spa(a,b);if(c){var d={card:b,Dp:c.element,yx:!1},e=Tpa(a,d);g.kb(a.A,e,0,d);c.ba(a.B,e);a.gm();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Oa(a.HN,d)):(c=1E3*a.context.ca.getCurrentTime(),5E3>c&&c>b.startMs&&a.MA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Oa(a.MA,d)),w3(a))}},Spa=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",V:b.displayDomain}:"";var e=Ipa(b);d={D:"div",W:["iv-card"],K:[{D:"a",I:"iv-click-target",N:{href:g3(b.url)},K:[k3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[j3("h2",void 0,b.title),e]}]}]};d=new g.V(d);m3(c,g.Fd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],N:{href:g3(b.url),"data-ytid":b.channelId},K:[k3(b.iA),{D:"div",I:"iv-card-content",
K:[n3(b),{D:"h2",I:"iv-card-primary-link",V:b.title},l3(c,b)]}]}]},d=new g.V(d),m3(c,g.Fd("iv-click-target",d.element),b,b.url),d;case "episode":return Hpa(a.H,b,"iv-card-episode");case "movie":return Hpa(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",N:{href:g3(b.url)},K:[k3(b.ai,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[n3(b),
j3("h2","iv-card-primary-link",b.title),l3(c,b)]}]}]},d=new g.V(d),m3(c,g.Fd("iv-click-target",d.element),b,b.url),d;case "poll":return Gpa(a.H,b);case "productListing":c=a.H;var f=!g.$a(b.offers);d=["iv-card"];e="";var k=Ipa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",V:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",V:f.merchant}),k={D:"div",K:k});d={D:"div",W:d,N:{tabindex:"0"},K:[{D:"a",
W:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:g3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",V:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",N:{href:g3(b.url)},K:[j3("h2",e,b.title),k]}]}]};d=new g.V(d);
e=g.Sd("span");g.be(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.qb(e,"adInfo");m3(c,g.Fd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"LIVE NOW"}:"",d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",N:{href:g3(b.url)},K:[k3(b.ai,b.videoDuration?{D:"span",I:"iv-card-video-duration",V:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[n3(b),j3("h2","iv-card-primary-link",b.title),l3(c,b),d]}]}]},d=new g.V(d),m3(c,g.Fd("iv-click-target",d.element),b,b.url),d}return null},Tpa=function(a,b){if(0==a.A.length)return 0;
var c=g.Wa(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Upa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.si)(a.A,function(b){return"productListing"==b.card.type})},w3=function(a){g.L(g.pL(a.w),"ytp-cards-shopping-active",Upa(a))},Vpa=function(a,b){if(a.U.Ia()){var c=new Q2([0,
a.B.scrollTop],[0,b.Dp.offsetTop],600,Zoa);a.context.w.ha(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ha(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.OC(a.U,!0),a.B.scrollTop=b.Dp.offsetTop,g.OC(a.U,!1)},x3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Ppa=function(a,b){return g.Va(a.A,function(c){return c.card.id==b})},y3=function(a,b,c){o3.call(this,a,b);
this.annotation=c;this.isActive=!1},Wpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z3=function(a,b,c){y3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},A3=function(a,b,c){y3.call(this,a,b,c);
this.M=this.C=this.J=!1;this.G=5E3;this.B=null;this.H=g.Rd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Lh(this.A,!1);g.Lh(this.w,!0)},700,this);
g.C(this,this.F)},Xpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=ypa(a.annotation),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.mj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Xc(f,g3(e)),a.u=f):a.u=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.gb.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var q=g.Rd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.mj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.mj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),
m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.mj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Rd("DIV","iv-promo-actions");a.w=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ha(a.w,"click",g.Oa(a.yq,5E3),a);c.appendChild(a.w);g.Lh(a.w,!1);
a.context.o.ha(a.o,"mouseover",a.xE,a);a.context.o.ha(a.o,"mouseout",a.wE,a);a.context.o.ha(a.o,"touchend",g.Oa(a.yq,5E3),a);a.A=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ha(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.qE:a.pE,a);c.appendChild(a.A);g.kn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},Ypa=function(a){a.C||a.M||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},Zpa=function(a){a.F.stop();
a.C&&(g.mn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Lh(a.w,!1),g.Lh(a.A,!0))},$pa=function(a,b){a.B||(a.B=g.yf(function(){B3(this);
Ypa(this)},b,a))},B3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},C3=function(a){g.AP.call(this,a);
this.M=!1;this.H=0;this.F={};this.U=new Bpa(a);this.B=new g.P(this);g.C(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.vL,this);this.subscribe("resize",this.eo,this);this.player.P().F.subscribe("vast_info_card_add",this.Uz,this);this.T=new g.P(this);g.C(this,this.T);this.O=g.Rd("DIV","video-custom-annotations");this.u=new g.V({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.JL(this.player,this.u.element,4);this.u.hide();this.A=new g.V({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.A);g.Ud(this.A.element,g.Rd("DIV","video-annotations",
this.O));this.G=this.o=null;this.J=[];aqa(this)&&this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ie(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},bqa=function(){var a=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Lh(a,!1);return a},cqa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},aqa=function(a){var b=a.player.P();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.MB||b.F.get(a.videoId)||g.R(b.experiments,"allow_skip_annotations_invideo")&&(g.XB(a)||g.YB(a))?!0:!1},dqa=function(a,b,c){a.M=!0;
a.C=g.Lp(b,c)},eqa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(eqa(a,e))}return c},fqa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},iqa=function(a){var b=a.player.getVideoData();
if(b.Pd){var c=a.player.P().F.get(b.videoId);if(c){var d={format:"XML",Jd:{},method:"POST",withCredentials:!0};d.jd=(0,g.x)(function(e,f,k){fqa(this,e,f)||(e=g.Fp(k)&&k.responseXML?k.responseXML:null)&&D3(this,e)},a,a.H,b.videoId);
g.gp()&&(d.jd=gqa(a,d.jd));d.xb={ic_only:"1"};hqa(d,c);a.M=!0;g.Lp(b.Pd,d)}}},hqa=function(a,b){a.method="POST";
a.xb=a.xb||{};b.km&&(a.xb.ic_coll=b.km);b.lm&&(a.xb.ic_xml=b.lm);b.zl&&(a.xb.ic_track=b.zl)},jqa=function(a){var b=new g.V({D:"div"});
g.Lh(b.element,!1);var c=new s3(a.player,b.element,E3(a));g.C(c,b);b.ba(a.u.element);c.nl();return c},E3=function(a){if(!a.G){var b=new T2(a);
g.C(a,b);var c=new g.s1(a);g.C(a,c);a.G=new Dpa(b,c,a.player.P(),a.player.getVideoData(),a.U,a.player,a.Zb)}return a.G},D3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.zs();if(e){var f=g.ys();f&&g.ks(e,f,[g.Yr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=eqa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=e3(k.type,kqa),t=e3(k.style,lqa),u=d3(k.data),y=0!=u.length?JSON.parse(u):{},B=ppa(k.action);f=n&&q?new wpa(n,q,t,B,y):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=bqa(),G=null;switch(m.type){case "branding":if(k.player.P().Qa)break;k.u.element.appendChild(D);G=new z3(D,E3(k),m);break;case "promotion":g.JL(k.player,D,4),G=new A3(D,E3(k),m)}G&&G.nl();if(k=G)g.C(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=jqa(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Uw:k.impression,click:k.click,close:k.close,hB:k.teaser_impression,Go:k.teaser_click},m=f.data.tracking_params||
{},D=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,iA:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:f3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};v3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):
null,ai:f.data.image_url,av:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,fF:!!f.data.is_paygated,oO:!!f.data.user_has_entitlement,url:f3({target:f.data.target||"new",value:f.data.url})};v3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):null,ai:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:f3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};v3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):null,title:f.data.title,choices:f.data.choices,re:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Xh:f.data.signin_url?f3({target:"current",value:f.data.signin_url}):null,zO:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};v3(c,f);break;case "productListing":f.data.signin_url&&(D=f3({target:"current",
value:f.data.signin_url}));G=[];for(var F=f.data.offers||[],E=0;E<F.length;E++)G.push(new Apa(g.dd(F[E].merchant),g.dd(F[E].price)));f={FS:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,em:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:f3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Xh:D,SS:f.data.signin_title?f.data.signin_title:null,RS:f.data.signin_message?f.data.signin_message:null,offers:G};v3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):null,bd:m.icon?g.Yr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,em:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:f3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};v3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Jb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ac:k,Qd:m.card?g.Yr(m.card):null,Gd:m.teaser?g.Yr(m.teaser):
null,bd:m.icon?g.Yr(m.icon):null,ai:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:f3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},v3(c,f)}}else Npa(a.o,f);c=!0}}}c&&(K2(a.player),a.eo())},mqa=function(a,b){var c=!1;
a.o||(a.o=jqa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Opa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.qA(b.headerText):"",g.be(c.za,d),c.T&&c.T.setAttribute("title",d),c.aa=b.trackingParams?g.Yr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Yr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.M=b.icon.infoCardIconRenderer.trackingParams?g.Yr(b.icon.infoCardIconRenderer.trackingParams):null,K2(a.player),a.eo())},
nqa=function(a,b,c,d,e){if(!a.player.P().Qa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new tpa("openUrl","click",new rpa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.qA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.qA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.qA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.qA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.qA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.qA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new wpa(c,"branding","branding",f,d);d=bqa();a.u.element.appendChild(d);f=new z3(d,E3(a),f);f.nl();g.C(f,f);a.F[c]=f}},gqa=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Oa.apply(window,c);this.J.push(g.ep(b))}},a)},N2={},O2=null;g.Qa(Q2,g.nn);g.h=Q2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;P2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.ie("play");-1==this.o&&this.ie("resume");this.o=1;var b=g.Na(this);b in N2||(N2[b]=this);apa();bpa(this,a);return!0};
g.h.stop=function(a){P2(this);this.o=0;a&&(this.progress=1);cpa(this,this.progress);this.ie("stop");this.A()};
g.h.pause=function(){1==this.o&&(P2(this),this.o=-1,this.ie("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.ie("destroy");Q2.Db.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.As=function(){this.ie("animate")};
g.h.ie=function(a){this.dispatchEvent(new dpa(a,this))};
g.Qa(dpa,g.le);g.Qa(R2,Q2);R2.prototype.C=g.Fa;R2.prototype.As=function(){this.C();R2.Db.As.call(this)};
R2.prototype.A=function(){this.C();R2.Db.A.call(this)};
R2.prototype.B=function(){this.C();R2.Db.B.call(this)};
g.Qa(S2,R2);S2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(T2,g.A);T2.prototype.ha=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Tq(a,b,c);this.o.push(a);return a};
T2.prototype.ir=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.cr(a,b,c);this.o.push(a);return a};
T2.prototype.Wa=function(a){g.Uq(a);g.cb(this.o,a)};
T2.prototype.X=function(){g.Uq(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.r(W2,g.AP);g.h=W2.prototype;g.h.load=function(){g.AP.prototype.load.call(this);if(!X2(this)){var a=g.WB(this.player.getVideoData());if(a)a=V2(a,gpa(this)),Y2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",jd:(0,g.x)(this.hK,this,a),Jd:{v:a},withCredentials:!0};this.M&&(a.Jd.ptype="embedded");var c=this.player.getVideoData().zm;c&&(a.xb={ad_tracking:c});if(b=g.VB(b))if(b=g.Cc(b),b=g.Ac(b))this.A=g.Lp(b,a)}}};
g.h.unload=function(){Y2(this,null);this.A&&(this.A.abort(),this.A=null);g.AP.prototype.unload.call(this)};
g.h.Fc=function(a,b){if(!X2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=V2(b,"new");Y2(this,c);return!0}return null};
g.h.getOptions=function(){return X2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.hK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=V2(c,gpa(this)))}Y2(this,c)};
g.h.Mx=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<oqa.length;f++){var k=Math.abs(b.width-oqa[f]);if(-1==e||d>=k)e=f,d=k}d=pqa[e];this.w&&g.qh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Jh(e.element,Math.round(k.width*a.width),f);g.yh(e.element,m,n);g.mn(e.element,qqa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.mn(e.element,pqa);g.K(e.element,d);(e=g.Ed(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.qh(e,"height",f+"px")}}}}};
g.h.OF=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())b3(this,this.u.impressionUrls),(a=g.zs())&&this.u.visualElement&&g.ls(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.pL(this.player),"ytp-ce-shown");b3(this,c.impressionUrls);(b=g.zs())&&g.ls(b,c.visualElement);this.player.P().Cb&&this.player.ma("endscreenelementshown",a)}};
g.h.PF=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.ln(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.ln(g.pL(this.player),"ytp-ce-shown");this.player.P().Cb&&this.player.ma("endscreenelementhidden",a)}};
g.h.VM=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.mn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.uz=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.jn(c,"ytp-ce-element");){g.jn(c,"subscribe-label")&&c3(this,a);if(g.jn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.jn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Fs(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.VN?(c3(this,a),this.LA(),this.player.pauseVideo(),c=g.Cc($2(this,a.targetUrl)),c=g.Ac(c),g.MM(c,void 0,a.Jb)):(c=this.player.getVideoData().jc,
c=(0,g.x)(this.PN,this,c,$2(this,a.targetUrl),a.Jb),c=(0,g.x)(this.LA,this,c),c3(this,a,c))}}};
g.h.PN=function(a,b,c){var d=g.rp(b);a&&d&&(d.v||d.list)?g.nT(this.player.app,d.v,c,d.list,!1,void 0):g.LM(b,c)};
g.h.zr=function(a,b){g.jn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.P().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),b3(this,b.TE),a3(this,b.id,!0))};
g.h.Fs=function(a,b){g.ln(a.element,"ytp-ce-element-hover");g.ln(a.element,"ytp-ce-force-expand");a3(this,b.id,!1)};
g.h.LA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var oqa=[346,426,470,506,570,640,853,1280,1920],pqa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),qqa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var spa={EP:"current",ZQ:"new"};var upa={CLOSE:"close",cR:"openUrl",HC:"subscribe"},vpa={yP:"click",CLOSE:"close",pQ:"hidden",HR:"rollOut",IR:"rollOver",LR:"shown"};var lqa={bP:"anchored",cC:"branding",CHANNEL:"channel",DP:"cta",rQ:"highlightText",IQ:"label",PLAYLIST:"playlist",uR:"popup",PR:"speech",HC:"subscribe",ZR:"title",VIDEO:"video",mS:"website"},kqa={cC:"branding",pP:"card",KP:"drawer",qQ:"highlight",PQ:"marker",zR:"promotion",TEXT:"text",oS:"widget"};i3.prototype.u=function(a,b){var c=g.ge(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
i3.prototype.A=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Xh)g.Gd("iv-card-sign-in-button",c).click();else{var d=parseInt(Xoa(b.target),10);if(null==a.re)a.choices[d].count++,a.re=d;else if(a.re!=d){var e=a.choices[a.re];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.re=d}else e=a.choices[a.re],e.count=Math.max(e.count-1,0),a.re=null;Fpa(a,c);g.Pp(this.o.videoData.Pd,{Jd:{action_poll_vote:1},xb:{poll_id:a.id,index:d,session_token:a.zO}});h3(this.o.logger,a.Ac.click,
void 0,5);(c=g.zs())&&a.Qd&&g.ms(c,a.Qd)}};g.r(o3,g.A);g.h=o3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.aE(a,b,{id:c});g.C(this,a);a.namespace="annotations_module";d&&Woa(a).subscribe("onEnter",d,this);e&&Woa(a).subscribe("onExit",e,this);g.FL(this.context.ca,[a])};
g.h.nl=function(){this.context.u.subscribe("resize",this.gm,this)};
g.h.mj=function(a,b,c,d,e,f){this.context.o.ha(a,"click",g.Oa(this.ln,b,c,d,e||[],f||0),this);this.context.o.ha(a,"touchstart",g.Oa(function(){this.Pt=!1}),this);
this.context.o.ha(a,"touchmove",g.Oa(function(){this.Pt=!0}),this)};
g.h.ln=function(a,b,c,d,e,f){if(this.Pt)return!1;f&&(f.stopPropagation(),f.preventDefault());Lpa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.o)};
g.h.gm=function(){};g.r(s3,o3);g.h=s3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.pL(this.w))?(a=g.Kh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.gm=function(){var a=this.isAvailable();g.Lh(this.o,a);g.L(g.pL(this.context.ca),"ytp-iv-drawer-enabled",a);K2(this.w)};
g.h.destroy=function(){var a=g.xL(g.kL(this.w));a&&a.yr(!1,void 0);try{g.pL(this.w).removeChild(this.F)}catch(b){}g.To(this.Y);g.Uq(this.oa);this.fa&&this.fa.dispose();this.G&&this.G.dispose();o3.prototype.destroy.call(this)};
g.h.lG=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.MA=function(a){if(!g.jn(g.pL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.zs(),c=this.u?this.u.card.bd:this.M;b&&c&&M2(b,[c]);this.u=a;w3(this)}if(b="none"!=this.o.style.display)2==this.context.ca.getPresentingPlayerType()?b=1==this.context.ca.getAdState():(b=this.context.ca.getPlayerState(),c=0==b&&0===this.context.ca.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.xL(g.kL(this.w)))&&c.yr(!0,b));
this.ua.isActive()||((!this.C||!this.Z.isActive()&&this.ea)&&Vpa(this,a),this.ua.start(910+a.card.teaserDurationMs))}};
g.h.HN=function(a){this.C||(this.u=a,w3(this),Vpa(this,a),q3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.kD=function(){if(this.C){h3(this.context.logger,x3(this).Ac.close);var a=g.zs();a&&this.O&&g.ms(a,this.O);r3(this)}};
g.h.yD=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.qF=function(){var a=g.zs(),b=x3(this);b=b?b.bd:this.M;a&&b&&L2(a,[b])};
g.h.pF=function(){var a=g.zs(),b=x3(this);b=b?b.bd:this.M;a&&b&&M2(a,[b])};
g.h.tF=function(){var a=x3(this);h3(this.context.logger,a.Ac.hB);var b=g.zs();b&&a&&L2(b,[a.Gd,a.bd])};
g.h.sF=function(){var a=g.zs(),b=x3(this);a&&b&&M2(a,[b.Gd])};
g.h.rF=function(a){var b=x3(this),c=g.zs();this.u?a?(a=this.context.logger,h3(a,b.Ac.Go),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Gd&&g.ms(c,b.Gd)):(a=this.context.logger,h3(a,b.Ac.Go),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.bd&&g.ms(c,b.bd)):(a=this.context.logger,h3(a,b.Ac.Go),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.M&&g.ms(c,this.M))};g.r(y3,o3);y3.prototype.nl=function(){o3.prototype.nl.call(this);Wpa(this)};
y3.prototype.show=function(){o3.prototype.show.call(this);var a=g.zs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&L2(a,[g.Yr(b.itct)])};
y3.prototype.hide=function(){o3.prototype.hide.call(this);var a=g.zs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&M2(a,[g.Yr(b.itct)])};g.r(z3,y3);g.h=z3.prototype;g.h.QN=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Kh(a);this.u||(g.Ih(a,e.width),g.Ih(b,e.width));g.qh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.qh(c,"right","1px");this.B=!0;g.Lh(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.SE=function(a,b){g.ln(this.o,"iv-branding-active");this.F=new g.J((0,g.x)(function(){g.Lh(a,!1);this.u||g.Ih(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){y3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Rd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Lh(this.w,!1);var b=g.Rd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=ypa(this.annotation))&&this.mj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Rd("DIV","iv-branding-context-name");
g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.fQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ca),this.u.ba(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Lh(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.qh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Oa(this.SE,c,d),500,this);g.C(this,this.A);this.context.o.ha(this.o,"mouseover",(0,g.x)(this.QN,this,c,d,b,a.image_height));this.context.o.ha(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Lh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Dh(a);c=g.Kh(a);b=(new g.nh(b.x,b.y,c.width,c.height)).width;g.yh(a,b);e=new S2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Yoa);g.C(this,e);this.context.w.ha(e,
"begin",g.Oa(g.Lh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(y3.prototype.hide.call(this),g.Lh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);y3.prototype.destroy.call(this)};g.r(A3,y3);g.h=A3.prototype;g.h.show=function(){this.isActive||(y3.prototype.show.call(this),this.J||(Xpa(this),this.J=!0),g.Lh(this.o,!0),g.yf(function(){g.ln(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,B3(this),Zpa(this),$pa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.ln=function(a,b,c,d,e,f){return this.C?!1:y3.prototype.ln.call(this,a,b,c,d,e,f)};
g.h.yq=function(a,b){b.stopPropagation();Zpa(this);$pa(this,a);this.u.focus()};
g.h.xE=function(a){this.M=!0;this.yq(500,a)};
g.h.wE=function(){this.M=!1;Ypa(this)};
g.h.pE=function(a){a.stopPropagation();this.hide()};
g.h.qE=function(a){a.stopPropagation();B3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();y3.prototype.destroy.call(this)};g.r(C3,g.AP);g.h=C3.prototype;g.h.Fc=function(a,b){if(!cqa(this.player.P().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.r1(b);c&&D3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Qpa(this.o,b),K2(this.player)),!0}return null};
g.h.getOptions=function(){return cqa(this.player.P().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.eo=function(){if(this.A){var a=g.oL(this.player).getVideoContentRect(!0);g.Jh(this.A.element,a.width,a.height);g.yh(this.A.element,a.left,a.top)}if(this.o){var b=g.AL(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.vL=function(a){this.dc(a.state);g.W(a.state,2)&&(this.Bk()&&this.Kx()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.yr(!1))};
g.h.load=function(){g.AP.prototype.load.call(this);this.dc(g.rL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.jK,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.gp()&&(c=gqa(this,c));c={format:"XML",jd:c,onError:d,Jd:{}};a.isPharma&&(c.Jd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.P().F.get(b))&&hqa(c,b);b=b&&(b.lm||b.km);if(!a.Wl||b)a.Pd?dqa(this,a.Pd,c):(this.w=(0,g.x)(this.MF,this,c),this.player.addEventListener("videodatachange",this.w));g.JL(this.player,this.A.element,4);this.eo();(b=g.XB(a))&&mqa(this,b);(b=g.YB(a))&&b.featuredChannel&&nqa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.dc=function(a){a=!a.isCued()&&!g.W(a,1024);g.OC(this.u,a);g.OC(this.A,a)};
g.h.MF=function(a){var b=this.player.getVideoData();b.Pd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),dqa(this,b.Pd,a))};
g.h.unload=function(){g.PQ(this.player.app,"annotations_module",void 0);g.Lb(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,K2(this.player));this.M=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.AP.prototype.unload.call(this);g.LC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.jK=function(a,b,c){this.C=null;!fqa(this,b,a)&&(a=g.Fp(c)&&c.responseXML?c.responseXML:null)&&(D3(this,a),g.K(g.pL(this.player),"iv-module-loaded"))};
g.h.Uz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?iqa(this):this.load())};
g.h.Bk=function(){return!!this.o&&this.o.isAvailable()};
g.h.Kx=function(){this.Bk();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Bk();this.o&&(a?c?q3(this.o,c,b):q3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):r3(this.o))};
g.h.yr=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.P().F.unsubscribe("vast_info_card_add",this.Uz,this);g.ln(g.pL(this.player),"ytp-iv-drawer-open");for(var a=this.J,b=0,c=a.length;b<c;b++)g.hp(a[b]);this.J.length=0;g.AP.prototype.X.call(this)};g.PP.annotations_module=C3;g.PP.creatorendscreen=W2;})(_yt_player);
