(function(g){var window=this;var I3=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.yz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.F,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},J3=function(a){return a.o?a.o.languageCode:a.u},rqa=function(a,b){var c=new g.xz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},sqa=function(){this.u=[];
this.o=[]},K3=function(a,b){return b?a.o.concat(a.u):a.o},L3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Va(c,(0,g.x)(b.Ar,b))||c.push(b);break;default:c=a.o,g.Va(c,(0,g.x)(b.Ar,b))||c.push(b)}},M3=function(a){g.A.call(this);
this.gb=a;this.u=new sqa;this.B=[]},N3=function(a,b,c){M3.call(this,a);
this.o=null;this.B=b.gv;this.w=c},O3=function(){this.segments=[]},P3=function(a,b,c,d,e,f){g.A.call(this);
this.M=a;this.w=b;this.O=b.P();this.B=new O3;this.o=null;this.F=d;this.J=f;this.u=this.A=null;this.T=c;this.C=e||!1;this.G=new g.J(this.wx,1E3,this);g.C(this,this.G);this.H=new g.P(this);g.C(this,this.H);this.H.L(b,"SEEK_COMPLETE",this.py);this.py();this.wx()},tqa=function(a,b){b-=a.w.Ab();
var c=a.o;a.o=g.Ta(a.T.Lf(b).o);c!=a.o&&a.J&&a.J()},uqa=function(a,b){var c=g.xv(g.zy(b,a.M,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.kq(c,d,3,100).then((0,g.x)(a.QL,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.ob(c.segments,d);0<=e||0>e&&1===(-e-1)%2||(e=-e-1,0<e&&1===d-c.segments[e-1]&&e<c.segments.length&&1===c.segments[e]-d?(g.bb(c.segments,e),g.bb(c.segments,e-1)):0<e&&1===d-c.segments[e-1]?c.segments[e-1]=d:e<c.segments.length&&1===c.segments[e]-d?c.segments[e]=d:(g.kb(c.segments,e,0,d),g.kb(c.segments,e+1,0,d)))},Q3=function(a,b){M3.call(this,b.P());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.ey(this.F.P())&&!this.o.u},vqa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.BP(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.xz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},wqa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},xqa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.BP(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},R3=function(a,b,c,d,e){M3.call(this,e||null);
c=c||g.rp(a).hl||"";c=c.split("_").join("-");this.A=g.tp(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},S3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.aE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},T3=function(a,b,c,d,e){g.aE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},U3=function(a,b){g.C(a,b);
a.o.push(b)},yqa=function(a){a=void 0===a?{}:a;
var b="_"+V3++;return new T3(0,0x8000000000000,0,b,a)},W3=function(a,b,c,d,e,f){var k={};
g.Pa(k,b);g.Pa(k,a.params);g.Pa(k,c);var l={};g.Pa(l,b.Bb);a.params.Bb&&g.Pa(l,a.params.Bb);g.Pa(l,c.Bb);k.Bb=l;g.V.call(this,{D:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.Hd?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{D:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.T=!1;this.w=a;this.Y=this.U=null;this.La=e;this.Ha=f;this.F=null;this.aa=.96*e;this.xa=.96*f;this.u=k;this.Da=c;this.B=this.o["captions-text"];this.Aa=
null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*zqa(l);a=new g.Mr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.sH,this);a.subscribe("dragmove",this.rH,this);a.subscribe("dragend",this.qH,this);this.ua=this.ra=0;b="";this.u.windowOpacity&&(a=g.q1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":Aqa[this.u.textAlign]};
this.Aa&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.A=2==this.w.params.Hd||3==this.w.params.Hd)b=this.element,c="vertical-rl",1==this.u.Bt&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.qh(b,"-o-writing-mode",c),g.qh(b,"-webkit-writing-mode",c),g.qh(b,"writing-mode",c),g.qh(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.w.params.Hd&&(g.qh(b,"text-orientation",""),g.qh(b,"transform","rotate(180deg)"));g.qh(this.element,a);switch(this.u.Af){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},zqa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Bqa=function(a,b){var c={},d=b.background?b.background:a.u.Bb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Bb.backgroundOpacity;d=g.q1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*zqa(b)+"px";d=1;e=b.color||a.u.Bb.color;if(b.color||null!=b.textOpacity)e=g.q1(e),d=null==b.textOpacity?a.u.Bb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Fp&&(k=e=b.Fp);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Vp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Bb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ce&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.RE&&(c.visibility="hidden");1==b.Sw&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.gy||g.hy,3==a.w.params.Hd?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.Je||2==b.Je||3==b.Je||4==b.Je||5==b.Je)if(g.gy)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Je){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Cqa=function(a){a.F=g.Sd("SPAN");
g.qh(a.F,{display:"block"});g.K(a.F,"caption-visual-line");a.B.appendChild(a.F)},Dqa=function(a,b){var c=g.Sd("SPAN");
g.qh(c,{display:"inline-block","white-space":"pre-wrap"});g.qh(c,Bqa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.qh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.qh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Eqa=function(a,b,c){a.T=a.T||!!c;
var d={};g.Pa(d,a.u.Bb);g.Pa(d,c||b.o);g.Pa(d,a.Da.Bb);(c=!a.F)&&Cqa(a);for(var e=a.U&&a.Y&&g.$b(d,a.Y)?a.U:Dqa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(Cqa(a),e=Dqa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Td(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.gy||!g.uh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.uh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.Nd?g.qh(e,m,"1em"):g.qh(e,m,"0.5em")))}a.Y=d;a.U=e;a.C.push(b)},Fqa=function(){},Y3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new X3(this);this.C=new X3(this);this.o=[];this.clear()},Hqa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Yl:a,
Zl:b,result:0};a=Gqa[a];b=Gqa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{Yl:a,Zl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Yl:a,Zl:b,result:2};return{Yl:a,Zl:b,result:3}},Jqa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Iqa(a.B,b,c,d))},Kqa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Jqa(a,d.jv,d.kv,b):1==d.type&&a.w&496&&Iqa(a.C,d.jv,d.kv,b)}a.o.length=0},Z3=function(){this.o=0},$3=function(){this.u=this.w=this.o=0},a4=function(){this.timestamp=this.ge=0},b4=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new a4}this.o=this.u=this.row=0;this.style=new Z3;this.B=a;this.A=0},c4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.ge){0==c&&(c=m,d=q);n=String.fromCharCode(t.ge);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.ge||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.ge,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Pqa=function(a,b){switch(a){case 0:return Lqa[(b&127)-32];
case 1:return Mqa[b&15];case 2:return Nqa[b&31];case 3:return Oqa[b&31]}return 0},d4=function(a){return a.w[a.row][a.u]},e4=function(a,b,c){2<=b&&1<a.u&&(--a.u,d4(a).ge=0);
var d=d4(a);d.timestamp=a.B.u+0;d.ge=Pqa(b,c);32>a.u&&a.u++},Qqa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].sg(a.w[c+e][f])},f4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},g4=function(a){a.row=0<a.o?a.o:1;
a.u=1;f4(a,0,15)},h4=function(a){this.A=a;
this.B=0;this.style=new Z3;this.C=new b4(a);this.F=new b4(a);this.G=new b4(a);this.u=this.C;this.w=this.F;this.o=this.u},i4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:c4(d,c),g4(a.u),g4(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(c4(d,c),f4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},Rqa=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},Sqa=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},X3=function(a){this.u=a;
this.o=new $3;this.B=0;this.w=new h4(a);this.C=new h4(a);this.A=this.w},Iqa=function(a,b,c,d){a.o.update();
b=Hqa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Yl;c=b.Zl;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&e4(a,0,b),c&96&&e4(a,0,c),0!=b&&0!=c&&3==a.style.o&&c4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Qqa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));f4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:e4(b.o,0,32);break a;case 48:57==c?(d=b.o,d4(d).ge=0,32>d.u&&d.u++):e4(b.o,1,c&15)}break;case 2:c&32&&e4(b.o,2,c&31);break;case 3:c&32&&e4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Rqa(b);break;
case 33:d=b.o;1<d.u&&(--d.u,d4(d).ge=0);break;case 36:d=b.o;b=d4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:i4(b,2,d);break;case 38:i4(b,3,d);break;case 39:i4(b,4,d);break;case 40:e4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);g4(d);Sqa(b);break;case 43:Sqa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:c4(a,d)}f4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;c4(a,d);Qqa(a,b,b+1,a.o-1);f4(a,a.row,1)}break;case 46:f4(b.w,0,15);break;case 47:c4(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,Rqa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},Uqa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Ib){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[q.getAttribute("p")];l=Tqa(l.textContent,n.textContent,q.textContent,f.textContent,k);return new S3(a,b,e,c,l,d,m)}switch(m.Ib){case 9:case 10:m.Je=1;break;case 11:m.Je=2;break;case 12:m.Je=3;break;case 13:m.Je=4;break;case 14:m.Je=5}return new S3(a,b,e,c,l.textContent||"",d,m)},Tqa=function(a,b,c,d,e){var f=g.Vp(),k=f?
g.Sd("DIV"):g.Sd("RUBY"),l=g.Sd("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.Sd("DIV"):g.Sd("RP");a.textContent=b;k.appendChild(a);b=f?g.Sd("DIV"):g.Sd("RT");b.textContent=c;k.appendChild(b);c=e.Ib;if(10==c||11==c||12==c||13==c||14==c)if(g.qh(b,"text-emphasis-style","filled circle"),g.qh(b,"text-emphasis-color","currentcolor"),g.qh(b,"webkit-text-emphasis","filled circle"),e.Ib==e.Ib==11||13==e.Ib)g.qh(b,"webkit-text-emphasis-position","under left"),g.qh(b,"text-emphasis-position","under left");c=!0;if(4==e.Ib||7==e.Ib||12==e.Ib||14==
e.Ib)g.qh(k,"ruby-position","over"),g.qh(k,"-webkit-ruby-position","before");else if(5==e.Ib||6==e.Ib||11==e.Ib||13==e.Ib)g.qh(k,"ruby-position","under"),g.qh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.Sd("DIV"):g.Sd("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.qh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.qh(f,"display","none"),f=f.nextElementSibling,g.qh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.qh(k.lastElementChild,"display","none"),d?(g.qh(k,"padding-top","0.6em"),g.qh(f,"top","0")):(g.qh(k,"padding-bottom","0.6em"),g.qh(f,"bottom","0")));return k},j4=function(){g.A.apply(this,arguments)},k4=function(a){j4.call(this);
this.A={};this.H={};this.M={};this.B="_"+V3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},l4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},m4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},n4=function(a,b){var c=l4(a,b);
return void 0!=c?c:null},p4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return o4.test(c),c},Vqa=function(a,b){var c={},d=b.getAttribute("ws");
g.Pa(c,d?a.M[d]:a.C);d=n4(b,"mh");null!=d&&(c.Pi=d);d=n4(b,"ju");null!=d&&(c.textAlign=d);d=n4(b,"pd");null!=d&&(c.Hd=d);d=n4(b,"sd");null!=d&&(c.Bt=d);d=p4(b,"wfc");null!=d&&(c.windowColor=d);d=l4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},Wqa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Pa(c,a.H[d]);d=n4(b,"ap");null!=d&&(c.Af=d);d=l4(b,"cc");null!=d&&(c.qg=d);d=l4(b,"ah");null!=d&&(c.De=d);d=l4(b,"rc");null!=d&&(c.eg=d);d=l4(b,"av");null!=d&&(c.fg=d);return c},Xqa=function(a,b,c,d){var e={};
g.Pa(e,Wqa(a,b));g.Pa(e,Vqa(a,b));d?g.$b(e,a.C)?(d=a.B,e=a.C):d="_"+V3++:d=b.getAttribute("id")||"_"+V3++;a=l4(b,"t")+c;b=l4(b,"d")||0x8000000000000;if(2==e.Hd||3==e.Hd)c=e.eg,e.eg=e.qg,e.qg=c;return new T3(a,b,0,d,e)},q4=function(a){j4.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},Yqa=function(a,b,c,d,e){0==d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.eg=a);b=b.ccColCount;void 0!=b&&(f.qg=b);if(2===f.Hd||3===f.Hd)b=f.eg,f.eg=f.qg,f.qg=b;return new T3(c,d,0,e,f)},r4=function(a,b,c,d,e,f,k){W3.call(this,a,b,c,d,e,f,k);
this.type=1},s4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},t4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},u4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},v4=function(a,b){j4.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new Y3;this.o.w=1<<this.track},$qa=function(a){if("string"===typeof a)return!1;
a=new s4(a,8,0);return Zqa(a)},Zqa=function(a){if(!(a.o<a.u.byteLength)||1380139777!=u4(a))return!1;
a.version=t4(a);if(1<a.version)return!1;t4(a);t4(a);t4(a);return!0},w4=function(a,b,c,d,e,f,k){W3.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.H=this.ea=0;this.O=NaN;this.za=0;this.Ba=null;this.fa=new g.J(this.VL,433,this);g.C(this,this.fa);g.qh(this.element,"overflow","hidden")},ara=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},bra=function(a){if(isNaN(a.O)){var b=a.u.qg;
if(b){var c=g.Sd("SPAN");g.be(c,"\u2013".repeat(b));g.qh(c,Bqa(a,a.u.Bb));a.B.appendChild(c);a.O=c.offsetWidth;a.B.removeChild(c)}else a.O=0}return a.O},cra=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.Bt&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},dra=function(a){a.G=[].concat(g.fa(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.eg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.J=Math.max(bra(a),a.za,ara(a,a.B))},era=function(a,b){dra(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ea){var d=0<c&&0==a.ea;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.$m(a.fa));g.qh(a.B,"transform",cra(a,c));a.ea=c}dra(a)},x4=function(){j4.call(this)},fra=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ce=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new S3(b,c,d,e.id,q.nodeValue,f||0<n,g.Yb(l)?void 0:l),m.push(q),U3(e,q);else{var t={};g.Pa(t,l);fra(a,b,c,d,e,!0,q,t,m)}}},y4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},gra=function(a,b,c,d){d=Object.assign({Pi:0},d);
return new T3(a,b,c,"_"+V3++,d)},z4=function(a){g.A.call(this);
this.u=a;this.o=null},ira=function(a){var b={};
if(a=J3(a))b.lang=a,hra.test(a)&&(b.Hd=1);return b},C4=function(a){g.AP.call(this,a);
this.w=a.P();this.S=a.getVideoData();this.za=g.oL(a);this.U=a;var b=null,c=g.Rn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Bn(c));this.aa=b;this.A={Bb:{}};this.C={Bb:{}};this.M=[];this.O={};this.Z={};this.J=!1;this.ua=g.CP(this.S,this.U);this.Aa=!!this.S.captionTracks.length;this.Ba=!!this.S.Ij;this.fa="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.wl());this.xa=!(!b||!b.Yh());this.B=this.fa&&c&&!this.ua;this.H=!this.B&&this.fa&&this.xa&&this.ua;this.u=this.F=this.G=this.Y=this.ra=
null;this.ea=new z4(this.w);g.C(this,this.ea);c=b=this.o=null;this.B||(b=new g.Wm(this.AB,void 0,this),g.C(this,b),c=new g.J(this.vN,2E3,this),g.C(this,c));this.oa=b;this.ka=c;this.T=new g.P(this);g.C(this,this.T);this.B||this.T.L(a,"resize",this.Kt);this.T.L(a,"onPlaybackAudioChange",this.BJ);this.T.L(a,g.dE("captions"),this.ZF,this);this.T.L(a,"crx_captions",this.aG,this);A4(this,B4(this,"display-settings")||{})},D4=function(a){if(1==a.w.og||1==a.S.og||"alwayson"==g.QB(a.S,"yt:cc"))return!0;
if(2==a.w.og){var b=B4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().Cp;return"ON"==c||"on"==g.QB(a.S,"yt:cc")},E4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Fm||"FORCED_ON"==c.Cp},G4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ba?!1:a.Aa?!1:!0);c=K3(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.QB(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(J3(c[f])==d[e])return c[f];return a.F&&a.F.Np?a.F.Np:(d=c.find(function(k){return k.isDefault}))?d:c[0]||F4(a)}return null},F4=function(a){return a.F&&a.F.Fm},H4=function(a){var b=F4(a);
return!!b&&a.o==b},jra=function(a,b){for(var c=a.U.app.B.fb().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},J4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.J=c,a.J&&I4(a,"module-enabled",!!b));a.o=b;E4(a)&&(a.o=F4(a));a.load()},kra=function(a,b){var c=a.za.getVideoContentRect(!0).height;
if(!c)return null;var d=a.za.getPlayerSize();switch(null!=b.params.Pi?b.params.Pi:1<b.o.length?1:0){case 1:return new r4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new w4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new W3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},A4=function(a,b,c){var d=K4.Bb;
a.A={};g.Pa(a.A,K4);a.A.Bb={};g.Pa(a.A.Bb,d);a.C={Bb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;o4.test(f);e.Bb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;o4.test(f);e.Bb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||K4.windowColor;o4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Bb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ce?3:d.bold?1:d.Ce?2:0);f=f.Bb;switch(e){case 1:f.bold=!0;delete f.Ce;break;case 2:delete f.bold;f.Ce=!0;break;case 3:f.bold=!0;f.Ce=!0;break;default:delete f.bold,delete f.Ce}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=K4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Bb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bb.fontFamily=f;a.loaded&&a.Kt();c&&I4(a,"display-settings",b)},mra=function(a,b){if(b&&!a.G){var c=yqa({Hd:0,
lang:"en"});a.G=[c,new S3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.FL(a.player,a.G)}else!b&&a.G&&(lra(a,a.G),a.G=null)},lra=function(a,b){g.qT(a.player.app,b,void 0);
(0,g.z)(b,function(c){g.cb(this.M,c)},a);
g.Xm(a.oa)},B4=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},I4=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.vC.prototype.Jj=g.da(12,function(){for(var a=g.Ed(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Xd(a[b])});
g.kR.prototype.Jj=g.da(11,function(){this.o.Jj()});
g.vC.prototype.wl=g.da(10,function(){return!!this.o.textTracks});
g.kR.prototype.wl=g.da(9,function(){return this.o.wl()});
g.vC.prototype.Ej=g.da(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.kR.prototype.Ej=g.da(7,function(a){this.o.Ej(a)});
g.mC.prototype.Yh=g.da(6,function(){});
g.vC.prototype.Yh=g.da(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.kR.prototype.Yh=g.da(4,function(){return this.o.Yh()});
g.xz.prototype.Ar=g.da(2,function(a){return a?this.toString()==a.toString():!1});
g.Bt.prototype.Sm=g.da(1,function(a){return(a=this.If(a))?a.o:0});
g.Ry.prototype.Sm=g.da(0,function(){return 0});
var hra=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,o4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(M3,g.A);M3.prototype.hA=function(){return!1};
M3.prototype.X=function(){this.Wg();g.A.prototype.X.call(this)};
g.r(N3,M3);N3.prototype.qr=function(a,b,c){b=this.ak(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Wg();this.o=g.Lp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
N3.prototype.rr=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())L3(this.u,c.value);a()};
N3.prototype.ak=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.Vp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=J3(a));return g.tp(c,d)};
N3.prototype.Wg=function(){this.o&&this.o.abort()};
O3.prototype.contains=function(a){a=g.ob(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
O3.prototype.length=function(){return this.segments.length/2};
g.r(P3,g.A);g.h=P3.prototype;g.h.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.h.py=function(){tqa(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new O3;this.u&&(this.u.cancel(),this.u=null)};
g.h.wx=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Yf(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.Ti(a),a.o[0].duration?(this.B.contains(a.o[0].u)||uqa(this,a),this.o=g.Ta(a.o)):!g.R(this.O.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.Ab()<this.w.getCurrentTime()&&tqa(this,this.w.getCurrentTime()));this.G.start()};
g.h.QL=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Wy(a);c?(a=g.zy(this.A,this.M,{}),b=this.A,g.uy(b.u,a,c),b.requestId=a.get("req_id"),uqa(this,this.A)):(b||null===this.F||(c=this.A.o[0],this.C?this.F(a.response,1E3*(c.startTime+this.w.Ab())):this.F(a.responseText,1E3*(c.startTime+this.w.Ab()))),this.u=this.A=null)};
g.r(Q3,M3);g.h=Q3.prototype;g.h.qr=function(a,b,c){this.Wg();b=wqa(this,a.getId());b||(b=a.u,b=this.o.u?xqa(this,b,"386"):xqa(this,b));if(b){var d=1E3*(b.index.Sm(b.index.ze())-b.index.Sc(b.index.ze()));this.w=new P3(new g.py,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.ov(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.hA=function(){var a=this.A;this.A=!1;return a};
g.h.rr=function(a){var b;this.C?b=[new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?vqa(this,"386"):vqa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())L3(this.u,c.value);a()};
g.h.Wg=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.ak=function(){return""};
g.r(R3,M3);R3.prototype.qr=function(a,b,c){b=this.ak(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Wg();this.o=g.Lp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
R3.prototype.rr=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.tp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
L3(this.u,new g.xz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Wg();this.o=g.Lp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
R3.prototype.ak=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=J3(a));return c=g.tp(c,d)};
R3.prototype.Wg=function(){this.o&&this.o.abort()};var Aqa=["left","right","center","justify"];var K4={windowColor:"#080808",windowOpacity:0,textAlign:2,Af:7,De:50,fg:100,Bb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(S3,g.aE);S3.prototype.toString=function(){return g.aE.prototype.toString.call(this)};g.r(T3,g.aE);T3.prototype.toString=function(){return g.aE.prototype.toString.call(this)};
var V3=0;g.r(W3,g.V);g.h=W3.prototype;g.h.sH=function(a,b){var c=g.Hh(this.element,this.element.parentElement);this.ra=a-c.x;this.ua=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.rH=function(a,b){var c=g.Kh(this.element),d=a-this.ra-.02*this.La,e=b-this.ua-.02*this.Ha,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.qd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.qd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.qd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.qd(c,0,1);this.w.params.Af=l;this.w.params.fg=c;this.w.params.De=d;this.u.Af=l;this.u.fg=c;this.u.De=d;this.GA()};
g.h.qH=function(){g.ln(this.element,"ytp-dragging")};
g.h.GA=function(){this.Vh(this.C)};
g.h.Vh=function(a){var b=Math.min(this.kw(),this.aa),c=this.jw(),d="";3==this.w.params.Hd&&(d="rotate(180deg)");g.qh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.rp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.De+2;d=this.u.Af;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.fg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.qh(this.element,a)};
g.h.rp=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.T||this.C.length>b)b=0,this.T=!1,this.C=[],this.F=this.Y=this.U=null,g.Vd(this.B);for(;b<a.length;b++)Eqa(this,a[b])};
g.h.kw=function(){return 0};
g.h.jw=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};Fqa.prototype.B=function(){};Y3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
Y3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Gqa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Z3.prototype.set=function(a){this.o=a};
Z3.prototype.get=function(){return this.o};
$3.prototype.clear=function(){this.o=0};
$3.prototype.update=function(){this.o=2==this.o?1:0};
$3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
a4.prototype.sg=function(a){this.ge=a.ge;this.timestamp=a.timestamp};
a4.prototype.reset=function(){this.timestamp=this.ge=0};
b4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
b4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.ge?a+"_":a+String.fromCharCode(d.ge)}a+="\n"}return a};
b4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Lqa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Mqa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Nqa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Oqa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];h4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
X3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(j4,g.A);j4.prototype.reset=function(){};g.r(k4,j4);k4.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
k4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Pa(l,this.A[m]);m=m4(c,"b");null!=m&&(l.bold=
m);m=m4(c,"i");null!=m&&(l.Ce=m);m=m4(c,"u");null!=m&&(l.underline=m);m=n4(c,"et");null!=m&&(l.charEdgeStyle=m);m=n4(c,"of");null!=m&&(l.offset=m);m=p4(c,"bc");null!=m&&(l.background=m);m=p4(c,"ec");null!=m&&(l.Fp=m);m=p4(c,"fc");null!=m&&(l.color=m);m=n4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=l4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=l4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=l4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=n4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Ib=10<m?m-1:m);
c=n4(c,"hg");null!=c&&(l.Sw=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.M[d]=Vqa(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=Wqa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=Xqa(this,d,e,!1);g.C(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;
m=!!m4(d,"a");n=(l4(d,"t")||0)+n;var q=l4(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],y=[].concat(g.fa(d.childNodes));y.length&&(this.F=null!=d.getAttribute("d"));for(var B=0;B<y.length;B++){var D=y[B],G=void 0;0<B&&(m=!0);var F=void 0;1==D.nodeType&&(F=D);if(F&&"s"==F.tagName){if((D=this.A[F.getAttribute("p")])&&D.Ib&&(1==D.Ib?(D=y.slice(B,B+4),4==D.length&&(G=Uqa(n,q,l,m,
t,D,this.A),B+=3)):G=Uqa(n,q,l,m,t,[F],this.A)),!G){var E=F;G=n;F=q;D=l;var M=m,aa=t,eb=E.textContent?E.textContent:"",tc=this.A[E.getAttribute("p")];E=l4(E,"t")||0;G=new S3(G+E,F-E,aa,D,eb,M,tc)}}else G=new S3(n,q,t,l,D.textContent||"",m,u);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=Xqa(this,d,e,!0),g.C(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,U3(this.o,k),c.push(k)}e=c}else e=[];return e};var L4=new Map([[4095,"#fff"],[4080,"#ff0"],[240,"#0f0"],[255,"#0ff"],[15,"#00f"],[3855,"#f0f"],[3840,"#f00"],[526344,"#080808"]]),nra=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(q4,j4);q4.prototype.reset=function(){this.u.clear()};
q4.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Ce=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);f.ecEdgeColor&&(k.Fp=L4.get(f.ecEdgeColor)||"#fff");l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);f.fcForeColor&&
(k.color=L4.get(f.fcForeColor)||"#fff");f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);f.bcBackColor&&(k.background=L4.get(f.bcBackColor)||"#fff");f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Ib=10<l?l-1:l,k.Je=nra.get(k.Ib));f.hgHorizGroup&&(k.Sw=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=f.mhModeHint&&
(k.Pi=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Hd=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.Bt=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=L4.get(f.wfcWinFillColor)||"#fff"),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.De=f.ahHorPos),
void 0!=f.apPoint&&(l.Af=f.apPoint),void 0!=f.avVerPos&&(l.fg=f.avVerPos),void 0!=f.ccCols&&(l.qg=f.ccCols),void 0!=f.rcRows&&(l.eg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=Yqa(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+V3++,l=Yqa(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,q=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var y=t[m],B=y.utf8;if(B){var D=y.tOffsetMs||0,G=null;y.pPenId&&(G=this.o.get(y.pPenId));if(2===(null!=l.params.Pi?l.params.Pi:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(y=G&&1===G.Ib)if(y=m,y+3>=t.length||!t[y+1].pPenId||!t[y+2].pPenId||!t[y+3].pPenId)y=!1;else{var F=t[y+1].pPenId;(F=this.o.get(F))&&F.Ib&&2==F.Ib?(F=t[y+2].pPenId,F=this.o.get(F),!F||!F.Ib||3>F.Ib?y=!1:(F=t[y+3].pPenId,y=(F=this.o.get(F))&&F.Ib&&2==F.Ib?!0:
!1)):y=!1}if(y){D=t[m+1].utf8;y=t[m+3].utf8;F=t[m+2].utf8;var E=this.o.get(t[m+2].pPenId);B=Tqa(B,D,F,y,E);n=new S3(e,f,q,k,B,n,G);m+=3}else n=new S3(e+D,f-D,q,l.id,B,n,G||u);n&&(d.push(n),U3(l,n))}n=!0}}}else d=[];return d};g.r(r4,W3);r4.prototype.rp=function(a){var b=this.w.o;W3.prototype.rp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Pa(d,c.o);g.Pa(d,ora);var e=c.o;var f=d}Eqa(this,c,d)}};
var ora={RE:!0};g.r(s4,Fqa);s4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+V3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new T3(c,d-c,5,f,{textAlign:0,Af:0,De:2.5*b,fg:5.33*a});e=new S3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(v4,j4);v4.prototype.w=function(a){a=new s4(a,a.byteLength,this.u);if(Zqa(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=u4(a)*(1E3/45):1==a.version&&(a.A=4294967296*u4(a)+u4(a)),a.C=t4(a);0<a.C;a.C--){var b=t4(a),c=t4(a),d=t4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,jv:c,kv:d,order:b.o.length}))}Kqa(this.o,a);return a.w}return[]};
v4.prototype.reset=function(){this.o.clear()};g.r(w4,W3);g.h=w4.prototype;g.h.GA=function(){g.an(this.fa)};
g.h.VL=function(){g.ln(this.element,"ytp-rollup-mode");this.Vh(this.Ba,!0)};
g.h.jw=function(){return this.A?this.J:this.H};
g.h.kw=function(){return this.A?this.H:this.J};
g.h.Vh=function(a,b){this.Ba=a;if(this.w.params.eg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.za=this.J;this.H=this.J=0;W3.prototype.Vh.call(this,a);era(this,b);W3.prototype.Vh.call(this,a)}else W3.prototype.Vh.call(this,a)};g.r(x4,j4);
x4.prototype.w=function(a,b){for(var c=[],d=a.split(pra),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!qra.test(f)){var l=M4.exec(f);if(l&&4<=l.length){var m=y4(l[1]),n=y4(l[2])-m;m+=k;var q,t=q=void 0,u=void 0,y=void 0,B=(l=l[3])?l.split(" "):[];l={textAlign:2};B=g.p(B);for(var D=B.next();!D.done;D=B.next())if(D=D.value.split(":"),2==D.length){var G=D[1];switch(D[0]){case "line":D=G.split(",");D[0].endsWith("%")&&(y=D[0],l.fg=Number.parseInt(y,10),2==D.length&&(u=D[1].trim()));break;case "position":D=G.split(",");
t=D[0];l.De=Number.parseInt(t,10);2==D.length&&(q=D[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.fg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.De=0;break;case 1:l.De=100;break;default:l.De=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Af=0>t||8<t?7:t;q=l;f=f.substring(M4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=gra(m,n,5,t),n=new S3(m,n,5,k.id,q,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),U3(k,n);else for(u=q.split(rra),1==u.length?(q=5,t=gra(m,n,q,t)):(y=q=6,t=Object.assign({qg:32},t),t=new T3(m,n,y,"_"+V3++,t)),c.push(t),y=m,l=0;l<u.length;l++)B=u[l],0==l%2?(D=g.r1("<html>"+B+"</html>"),D.getElementsByTagName("parsererror").length?
(G=D.createElement("span"),G.appendChild(D.createTextNode(B))):G=D.firstChild,fra(this,y,n-(y-m),q,t,0<l,G,f,c)):y=y4(B)+k}M4.lastIndex=0}}return c};
var qra=/^NOTE/,pra=/(?:\r\n|\r|\n){2,}/,M4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),rra=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(z4,g.A);z4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
z4.prototype.reset=function(){this.o&&this.o.reset()};
z4.prototype.X=function(){this.clear();g.A.prototype.X.call(this)};g.r(C4,g.AP);g.h=C4.prototype;g.h.X=function(){if(this.B||this.H){var a=this.U.app.B;a&&a.Jj()}else mra(this,!1);g.AP.prototype.X.call(this)};
g.h.load=function(){g.AP.prototype.load.call(this);var a=!g.R(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u){if(this.o){this.ea.clear();if(this.B)jra(this,!0);else if(3!=this.player.getPresentingPlayerType()){var b=g.R(this.w.experiments,"html5_enable_json_subtitle")?"json3":"srv3";this.u.qr(this.o,b,(0,g.x)(this.CM,this))}!a||this.B||this.H||H4(this)||this.player.ma("captionschanged",I3(this.o))}a||(this.o&&!H4(this)?this.player.ma("captionschanged",
I3(this.o)):this.player.ma("onCaptionsTrackListChanged"))}else this.ua?b=new Q3(this.S.na,this.player):this.Aa?b=new N3(this.w,this.S,this.player.getAudioTrack()):b=new R3(this.S.Ij,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.QB(this.S,"yt:cc_default_lang")||this.w.oc,this.S.Ap,this.w),this.u=b,g.C(this,this.u),b.rr((0,g.x)(this.BM,this))};
g.h.unload=function(){this.B&&this.o?jra(this,!1):(this.ka&&g.bn(this.ka),g.PQ(this.player.app,"captions",void 0),this.M=[],this.u&&this.u.Wg(),this.ea.clear(),this.G&&g.FL(this.player,this.G),this.Kt());g.AP.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.PI(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.fa?this.B||this.H:E4(this)||D4(this))&&this.load()};
g.h.BM=function(){var a;this.J||D4(this)?a=G4(this,this.J):E4(this)&&(a=F4(this));if(this.B||this.H){for(var b=K3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.yz(e),srclang:J3(e),id:e.toString()};this.H||(f.src=this.u.ak(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Rd("TRACK",f))}a=this.U.app.B;a.Ej(c);c=a.fb();this.xa&&this.T.L(c.textTracks,"change",this.DM)}else!this.o&&a&&J4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.DM=function(){for(var a=this.U.app.B.fb().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=K3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&J4(this,b,!0)};
g.h.gO=function(){!this.o&&this.B||this.unload()};
g.h.CM=function(a,b,c,d){if(a){this.u.hA()&&(this.M=[],g.PQ(this.U.app,"captions",void 0),g.Xm(this.oa),this.ea.reset());var e=this.ea;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.$t(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!$qa(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&
63)}else if(239<m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var u=a,y=d;if(!$qa(u))throw Error("Invalid binary caption track data");e.o||(e.o=new v4(y,b));var B=e.o.w(u,c)}else{if("WEBVTT"==a.substring(0,6))b=a,e.o||(e.o=new x4),y=e.o.w(b,c),.01>Math.random()&&
g.Go(Error("Deprecated subtitles format in web player: WebVTT")),u=y;else b:{y=a;if(g.R(e.u.experiments,"html5_enable_json_subtitle"))try{e.o||(e.o=new q4(ira(b)));u=e.o.w(y,c);break b}catch(eb){g.O(eb);u=[];break b}var D=g.r1(y);if(!D||!D.firstChild){var G=Error("Invalid caption track data");G.params=y;throw G;}if("timedtext"==D.firstChild.tagName){if(3==parseInt(D.firstChild.getAttribute("format"),10)){e.o||(e.o=new k4(ira(b),e.u));u=e.o.w(D,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");
F.params=y;throw F;}if("transcript"==D.firstChild.tagName){var E=Error("Unsupported subtitles format in web player (Format1)");E.params=y;throw E;}var M=Error("Invalid caption track data");M.params=y;throw M;}B=u}var aa=B}catch(eb){g.O(eb),e.clear(),aa=[]}else aa=[];g.FL(this.player,aa);!this.J||this.H||H4(this)||g.Ux(this.w)||g.Vx(this.w)||(g.bn(this.ka),aa=yqa({Af:0,De:5,fg:5,eg:2,textAlign:0,Hd:0,lang:"en"}),this.Y=[aa],e=["Click "," for settings"],this.ra||(B=new g.KC(g.BM()),g.C(this,B),this.ra=
B.element),B=aa.end-aa.start,(b=g.yz(this.o))&&this.Y.push(new S3(aa.start,B,0,aa.id,b)),this.Y.push(new S3(aa.start,B,0,aa.id,e[0]),new S3(aa.start,B,0,aa.id,this.ra,!0),new S3(aa.start,B,0,aa.id,e[1],!0)),g.FL(this.player,this.Y),g.$m(this.ka));!this.J||this.H||H4(this)||(I4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(aa=g.U(this.player.app))&&g.PI(aa.B));this.J=!1}};
g.h.ZF=function(a){this.M.push(a);g.Xm(this.oa)};
g.h.aG=function(a){g.cb(this.M,a);this.u instanceof Q3&&this.u.C&&g.qT(this.player.app,[a],void 0);g.Xm(this.oa)};
g.h.nN=function(a){if(a instanceof T3){var b=this.O[a.id];b&&b.w!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=kra(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.vN=function(){lra(this,this.Y);this.Y=null};
g.h.AB=function(){this.oa.stop();g.Zb(this.Z);this.M.sort(g.cE);var a=this.M;if(this.G){var b=(0,g.Yd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.z)(a,this.nN,this);g.Lb(this.O,function(c,d){this.Z[d]?(c.element.parentNode||g.JL(this.player,c.element,4),c.Vh(this.Z[d])):(c.dispose(),delete this.O[d])},this)};
g.h.AN=function(){A4(this,{},!0);g.R(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.hE=function(){var a=K4.Bb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ce?3:a.bold?1:a.Ce?2:0,textOpacity:a.textOpacity,windowColor:K4.windowColor,windowOpacity:K4.windowOpacity};var b=B4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.FB=function(a,b){var c={};g.Pa(c,B4(this,"display-settings"));g.Pa(c,a);A4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Kt=function(){!this.B&&this.loaded&&(g.Lb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.AB())};
g.h.Fc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qd(b,-2,4);this.FB({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&J4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.Cb&&I4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.La(b))break;if(g.Yb(b)){J4(this,null,!0);break}for(var d=K3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?rqa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||J4(this,c,!0)}else return this.loaded&&this.o&&!H4(this)?I3(this.o):{};return"";case "tracklist":return this.u?(0,g.Ic)(K3(this.u.u,!(!b||!b.includeAsr)),function(k){return I3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||mra(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.Cb&&a.push("stickyLoading");return a};
g.h.YF=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.ZN=function(){this.loaded&&this.o&&!H4(this)?(I4(this,"module-enabled",!1),this.unload(),E4(this,!0)&&J4(this,F4(this),!1)):J4(this,H4(this)||!this.o?G4(this,!0):this.o,!0)};
g.h.BJ=function(){var a=H4(this);E4(this,a)?J4(this,this.player.getAudioTrack().Fm,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.B||this.H:E4(this)||D4(this))&&(a?J4(this,G4(this),!1):this.load()))};g.PP.captions=C4;})(_yt_player);
